-- ==========================================
-- REPAIR HABITS & HABIT_LOGS SCHEMA
-- ==========================================

-- 1. Ensure habits table has user_id
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='habits' AND column_name='user_id') THEN
        ALTER TABLE public.habits ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 2. Create or Update habit_logs
CREATE TABLE IF NOT EXISTS public.habit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- Ensure all required columns exist in habit_logs
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='habit_logs' AND column_name='user_id') THEN
        ALTER TABLE public.habit_logs ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='habit_logs' AND column_name='habit_id') THEN
        ALTER TABLE public.habit_logs ADD COLUMN habit_id TEXT REFERENCES public.habits(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='habit_logs' AND column_name='date') THEN
        ALTER TABLE public.habit_logs ADD COLUMN date DATE NOT NULL DEFAULT CURRENT_DATE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='habit_logs' AND column_name='completed') THEN
        ALTER TABLE public.habit_logs ADD COLUMN completed BOOLEAN DEFAULT TRUE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='habit_logs' AND column_name='count') THEN
        ALTER TABLE public.habit_logs ADD COLUMN count INTEGER DEFAULT 1;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='habit_logs' AND column_name='created_at') THEN
        ALTER TABLE public.habit_logs ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW();
    END IF;
END $$;

-- 3. Ensure unique constraint for habit_logs (habit_id + date)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'habit_logs_habit_id_date_key') THEN
        ALTER TABLE public.habit_logs ADD CONSTRAINT habit_logs_habit_id_date_key UNIQUE(habit_id, date);
    END IF;
END $$;

-- 4. Enable RLS and setup policies
ALTER TABLE public.habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.habit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own habits" ON public.habits;
CREATE POLICY "Users can manage their own habits" ON public.habits
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage their own habit logs" ON public.habit_logs;
CREATE POLICY "Users can manage their own habit logs" ON public.habit_logs
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 5. Realtime Publication
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE habits;
        ALTER PUBLICATION supabase_realtime ADD TABLE habit_logs;
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;
