-- ==============================================================================
-- ENSURE HABITS & HABIT_LOGS TABLES EXIST
-- This migration creates the habits tracking system if not exists
-- ==============================================================================

-- Create Habits Table
CREATE TABLE IF NOT EXISTS habits (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  frequency TEXT NOT NULL DEFAULT 'daily',
  custom_days TEXT[],
  times_per_day INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Habit Logs Table (for history)
CREATE TABLE IF NOT EXISTS habit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  habit_id TEXT REFERENCES habits(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  completed BOOLEAN DEFAULT TRUE,
  count INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(habit_id, date)
);

-- Enable RLS
ALTER TABLE habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_logs ENABLE ROW LEVEL SECURITY;

-- Create Policies (if not exist)
DO $$ BEGIN
    CREATE POLICY "Users can manage their own habits" ON habits
        FOR ALL USING (auth.uid() = user_id)
        WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN OTHERS THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Users can manage their own habit logs" ON habit_logs
        FOR ALL USING (auth.uid() = user_id)
        WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Add realtime
DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE habits;
    ALTER PUBLICATION supabase_realtime ADD TABLE habit_logs;
EXCEPTION WHEN OTHERS THEN NULL; END $$;
