-- Create Shopping Items Table
CREATE TABLE IF NOT EXISTS shopping_items (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  quantity NUMERIC DEFAULT 1,
  unit TEXT DEFAULT 'unit',
  completed BOOLEAN DEFAULT FALSE,
  deadline TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Habits Table
CREATE TABLE IF NOT EXISTS habits (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  frequency TEXT NOT NULL DEFAULT 'daily',
  custom_days TEXT[],
  times_per_day INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Habit Logs Table (for history)
CREATE TABLE IF NOT EXISTS habit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  habit_id TEXT REFERENCES habits(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  completed BOOLEAN DEFAULT TRUE,
  count INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(habit_id, date)
);

-- Create Medications Table
CREATE TABLE IF NOT EXISTS medications (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  time TEXT,
  frequency TEXT NOT NULL DEFAULT 'daily',
  custom_days TEXT[],
  start_date DATE,
  end_date DATE,
  is_permanent BOOLEAN DEFAULT FALSE,
  reminder BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Medication Logs Table (for taken history)
CREATE TABLE IF NOT EXISTS medication_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medication_id TEXT REFERENCES medications(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  taken BOOLEAN DEFAULT TRUE,
  taken_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(medication_id, date)
);

-- Enable RLS
ALTER TABLE shopping_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE medication_logs ENABLE ROW LEVEL SECURITY;

-- Creating Policies (Assuming simple user isolation)

-- Shopping Items
CREATE POLICY "Users can manage their own shopping items" ON shopping_items
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Habits
CREATE POLICY "Users can manage their own habits" ON habits
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Habit Logs
CREATE POLICY "Users can manage their own habit logs" ON habit_logs
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Medications
CREATE POLICY "Users can manage their own medications" ON medications
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Medication Logs
CREATE POLICY "Users can manage their own medication logs" ON medication_logs
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Realtime
alter publication supabase_realtime add table shopping_items;
alter publication supabase_realtime add table habits;
alter publication supabase_realtime add table habit_logs;
alter publication supabase_realtime add table medications;
alter publication supabase_realtime add table medication_logs;
